export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_BAN_REQUEST = "USER_BAN_REQUEST";
export const USER_BAN_SUCCESS = "USER_BAN_SUCCESS";
export const USER_BAN_FAIL = "USER_BAN_FAIL";
export const USER_BAN_RESET = "USER_BAN_USER";

export const USER_UNBAN_REQUEST = "USER_UNBAN_REQUEST";
export const USER_UNBAN_SUCCESS = "USER_UNBAN_SUCCESS";
export const USER_UNBAN_FAIL = "USER_UNBAN_FAIL";
export const USER_UNBAN_RESET = "USER_UNBAN_USER";

export const SHOP_LIST_REQUEST = "SHOP_LIST_REQUEST";
export const SHOP_LIST_SUCCESS = "SHOP_LIST_SUCCESS";
export const SHOP_LIST_FAIL = "SHOP_LIST_FAIL";
export const SHOP_LIST_RESET = "SHOP_LIST_RESET";


export const SHOP_BAN_SUCCESS = "SHOP_BAN_SUCCESS";
export const SHOP_BAN_REQUEST = "SHOP_BAN_REQUEST";
export const SHOP_BAN_FAIL = "SHOP_BAN_FAIL";
export const SHOP_BAN_RESET = "SHOP_BAN_USER";

export const SHOP_UNBAN_REQUEST = "SHOP_UNBAN_REQUEST";
export const SHOP_UNBAN_SUCCESS = "SHOP_UNBAN_SUCCESS";
export const SHOP_UNBAN_FAIL = "SHOP_UNBAN_FAIL";
export const SHOP_UNBAN_RESET = "SHOP_UNBAN_USER";